Rpethkar
Rajashree-Pethkar/frontend-homework pull request #2
Opened 2023-04-26 22:33 UTC by Rajashree-Pethkar

Homework 2:

1. Completed Exercise 01 - Flexbox Froggy
2. Completed Exercise 02 - Grid Garden
3. Completed Exercise 03 - Count
    - Set the background color as per the homework
    - Added bootstrap styling
    - Implemented the highlight functionality
4. Completed Exercise 04 - Background
    - Implemented color changes functionality
    - Added the event listeners
    - Added bootstrap styling
    - Updated the html code as per homework
5. Completed Exercise 05 - Form
    - Added bootstrap styling
    - Updated the html as per the homework

2023-04-28 19:34 UTC, Pranav-PSU commented on hw2/03-count.js
> +    let regexp = new RegExp(`\\b(${inputText})\\b`, "ig");
Const instead of let can be used because regexp is not getting reassigned

2023-04-28 19:37 UTC, Pranav-PSU commented on hw2/03-count.js
> +
Consider formatting this file with prettier

2023-04-28 19:41 UTC, Pranav-PSU commented on hw2/05-form.html
> +          <label for="registrationStatus" class="form-label h6"><strong>Registration Status:</strong></label>
The value of the for attribute of the label element must be the ID of a form control.

2023-04-28 19:44 UTC, Pranav-PSU requested changes
Good job with the homework. A couple of minor changes are suggested. Otherwise, everything looks good.

2023-04-28 23:58 UTC, rohan-singh1 approved these changes
Issues have already been pointed out and addressed. Looks good.

2023-04-30 21:07 UTC, Pranav-PSU approved these changes

2023-04-30 21:14 UTC, merged